=== sunknudsen/tube-manager/schemas/tube-manager.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/sunknudsen/tube-manager/master/schemas/tube-manager.schema.json",
  "title": "tube-manager dataset",
  "description": "Schema for tube-manager dataset",
  "type": "object",
  "definitions": {
    "labelAndUrl": {
      "type": "object",
      "properties": {
        "label": {
          "description": "Label",
          "type": "string"
        },
        "url": {
          "description": "URL",
          "type": "string"
        }
      },
      "required": ["label", "url"],
      "additionalProperties": false
    },
    "affiliateProduct": {
      "type": "object",
      "properties": {
        "label": {
          "description": "Label",
          "type": "string"
        },
        "url": {
          "anyOf": [
            {
              "description": "URL",
              "type": "string"
            },
            {
              "description": "URL list",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "label": {
                    "description": "Label",
                    "type": "string"
                  },
                  "url": {
                    "description": "URL",
                    "type": "string"
                  }
                }
              },
              "uniqueItems": true
            }
          ]
        }
      },
      "required": ["label", "url"],
      "additionalProperties": false
    }
  },
  "properties": {
    "headings": {
      "description": "Heading titles",
      "type": "object",
      "properties": {
        "sections": {
          "description": "Sections title",
          "type": "string"
        },
        "suggestedVideos": {
          "description": "Suggested videos title",
          "type": "string"
        },
        "links": {
          "description": "Links title",
          "type": "string"
        },
        "credits": {
          "description": "Credits title",
          "type": "string"
        },
        "affiliateLinks": {
          "description": "Affiliate links title",
          "type": "string"
        },
        "footnotes": {
          "description": "Footnotes title",
          "type": "string"
        },
        "support": {
          "description": "Support title",
          "type": "string"
        }
      },
      "required": [
        "sections",
        "suggestedVideos",
        "links",
        "credits",
        "affiliateLinks",
        "footnotes"
      ],
      "additionalProperties": false
    },
    "separator": {
      "description": "Heading separator",
      "type": "string"
    },
    "affiliateLinks": {
      "description": "Affiliate links",
      "type": "object",
      "patternProperties": {
        "^.*$": {
          "description": "Platform",
          "type": "object",
          "patternProperties": {
            "^.*$": {
              "description": "Product",
              "$ref": "#/definitions/affiliateProduct"
            }
          }
        }
      }
    },
    "videos": {
      "description": "Videos",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "ID",
            "type": "string"
          },
          "publishedAt": {
            "description": "Published at",
            "type": "string"
          },
          "title": {
            "description": "Title",
            "type": "string"
          },
          "description": {
            "description": "Description",
            "type": "string"
          },
          "tags": {
            "description": "Tags",
            "type": "array",
            "items": {
              "description": "Tag",
              "type": "string"
            },
            "uniqueItems": true
          },
          "categoryId": {
            "description": "Category ID",
            "type": "string"
          },
          "sections": {
            "description": "Sections",
            "type": "array",
            "items": {
              "description": "Section",
              "type": "object",
              "properties": {
                "timestamp": {
                  "description": "Timestamp",
                  "type": "string"
                },
                "label": {
                  "description": "Label",
                  "type": "string"
                }
              }
            }
          },
          "suggestedVideos": {
            "description": "Suggested videos",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "description": "Suggested video",
                  "type": "string"
                },
                {
                  "description": "Suggested video with label",
                  "$ref": "#/definitions/labelAndUrl"
                }
              ]
            }
          },
          "links": {
            "description": "Links",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "description": "Link",
                  "type": "string"
                },
                {
                  "description": "Link with label",
                  "$ref": "#/definitions/labelAndUrl"
                }
              ]
            }
          },
          "credits": {
            "description": "Credits",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "description": "Credit",
                  "type": "string"
                },
                {
                  "description": "Credit with label",
                  "$ref": "#/definitions/labelAndUrl"
                }
              ]
            }
          },
          "affiliateLinks": {
            "description": "Affiliate links",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "description": "Affiliate link",
                  "type": "string"
                },
                {
                  "description": "Affiliate product",
                  "$ref": "#/definitions/affiliateProduct"
                }
              ]
            }
          },
          "footnotes": {
            "description": "Footnotes",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "description": "Footnote",
                  "type": "string"
                },
                {
                  "description": "Footnote with type",
                  "type": "object",
                  "properties": {
                    "type": {
                      "description": "Type",
                      "type": "string",
                      "enum": ["", "warning"]
                    },
                    "timestamp": {
                      "description": "Timestamp",
                      "type": "string"
                    },
                    "message": {
                      "description": "Message",
                      "type": "string"
                    }
                  },
                  "required": ["type", "timestamp", "message"],
                  "additionalProperties": false
                }
              ]
            }
          },
          "support": {
            "description": "Support",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "description": "Channel",
                  "type": "string"
                },
                {
                  "description": "Channel with label",
                  "$ref": "#/definitions/labelAndUrl"
                }
              ]
            }
          },
          "thumbnailHash": {
            "description": "Thumbnail hash",
            "type": "string"
          }
        },
        "required": [
          "id",
          "publishedAt",
          "title",
          "description",
          "tags",
          "categoryId",
          "sections",
          "suggestedVideos",
          "links",
          "credits",
          "affiliateLinks",
          "footnotes"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": ["headings", "separator", "affiliateLinks", "videos"],
  "additionalProperties": false
}

=== sunknudsen/tube-manager/samples/tube-manager.json
{
  "headings": {
    "sections": "TL;DR",
    "suggestedVideos": "Suggested",
    "links": "Links",
    "credits": "Credits",
    "affiliateLinks": "Affiliate links",
    "footnotes": "Change log",
    "support": "Support"
  },
  "separator": "ðŸ‘‰",
  "affiliateLinks": {
    "amazon": {
      "brotherPrinter": {
        "label": "Brother HL-L2370DW printer",
        "url": [
          {
            "label": "USA",
            "url": "https://www.amazon.com/dp/B076Q1FK19?tag=sunknudsen06-20"
          }
        ]
      }
    }
  },
  "videos": [
    {
      "id": "YrUSJQq8WOA",
      "publishedAt": "2022-11-03T14:43:45Z",
      "title": "macOS stores a copy of everything one prints forever",
      "description": "In this episode, we explore how macOS stores a copy of everything one prints forever.",
      "tags": ["Privacy", "Security", "macOS"],
      "categoryId": "27",
      "sections": [],
      "suggestedVideos": [],
      "links": [
        {
          "label": "How to disable CUPS pinter job history on macOS",
          "url": "https://sunknudsen.com/privacy-guides/how-to-disable-cups-pinter-job-history-on-macos"
        },
        {
          "label": "Twitter (please follow @superbacked)",
          "url": "https://twitter.com/superbacked"
        },
        {
          "label": "Superbacked (join waiting list)",
          "url": "https://superbacked.com/"
        }
      ],
      "credits": [],
      "affiliateLinks": ["amazon.brotherPrinter"],
      "footnotes": [],
      "support": [
        {
          "label": "Support my research",
          "url": "https://sunknudsen.com/donate"
        }
      ],
      "thumbnailHash": "65c65f74ac181dcffc994d9f75ed88392bdcc434165bc59dda2a0553a0725ac6"
    }
  ]
}
